services:
  react_learning:
    container_name: react_learning
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../src:/var/www/react_learning
    ports:
      - "1029:1029"
    privileged: true
    labels:
      org.label-schema.group: "react_learning"
    working_dir: "/var/www/react_learning"
    command: sh -c "npm start"

version: '3'
volumes: {}